import Image from "next/image";
import styles from "./page.module.css";
import Hero from "/public/images/photos/hero.svg";
import Link from "next/link";

export const metadata = {
  title: "Alsamara Shop",
  description: "Generated by create next app",
};


export default function Home() {  
  return (
    <>
      <div className={styles.page_container}>
        <div className={styles.col}>
          <h1 className={styles.title}>Your Best e-commerce destination!</h1>
          <p className={styles.description}>
            on the internet. It is your bustling city center or brick-and-mortar
            shop translated into zeroes and ones on the internet superhighway.
          </p>
          <Link href="/products" className={styles.link}>
            Shop Now
          </Link>
        </div>
        <div className={styles.col}>
          <Image src={Hero} className={styles.image} alt="image" />
        </div>
      </div>
    </>
  );
}
